export type Agent = {
  id: number;
  name: string;
  role: string;
  icon: string;
  category: string;
  summary: string;
  responsibilities: string[];
  knowledge?: string[];
  supports?: string[];
};

export const AGENTS: Agent[] = [
  { id: 1, name: "Executive Orchestrator", role: "Coordinator", icon: "Crown", category: "Core",
    summary: "Coordinates every other agent, plans work, delegates tasks, and merges outputs.",
    responsibilities: ["Understand project goals","Create implementation plan","Delegate work","Schedule tasks","Monitor progress","Detect blockers","Retry failed tasks","Merge outputs","Prioritize work","Estimate complexity","Resolve conflicts","Maintain project memory","Select the AI model for each task","Coordinate local and cloud execution"] },
  { id: 2, name: "Software Architect", role: "Architecture", icon: "Building2", category: "Design",
    summary: "Designs systems from clean architecture to event-driven microservices.",
    knowledge: ["System Design","Enterprise Architecture","Clean Architecture","DDD","Hexagonal Architecture","Microservices","Event Driven Architecture","CQRS","Event Sourcing","API Design","Database Design","Cloud Architecture"],
    responsibilities: ["Generate architecture","Choose frameworks","Design folder structures","Produce UML","ER Diagrams","Sequence diagrams","API specifications","Scalability planning"] },
  { id: 3, name: "Requirements Engineer", role: "Analysis", icon: "ClipboardList", category: "Design",
    summary: "Turns ideas into precise specifications and acceptance criteria.",
    responsibilities: ["Understand business requirements","Ask missing questions","Convert ideas into specifications","Produce SRS","User Stories","Acceptance Criteria","Functional Requirements","Non-functional Requirements"] },
  { id: 4, name: "Product Manager", role: "Product", icon: "Kanban", category: "Design",
    summary: "Prioritizes features, plans releases, decomposes work.",
    responsibilities: ["Prioritize features","Roadmaps","Releases","Sprint planning","Feature decomposition","MVP identification"] },
  { id: 5, name: "UI/UX Designer", role: "Design", icon: "Palette", category: "Design",
    summary: "Crafts accessible, responsive interfaces and design systems.",
    knowledge: ["Material UI","HIG","Tailwind","Bootstrap","Chakra","Ant Design","WCAG","Responsive Design"],
    responsibilities: ["Design screens","User flows","Wireframes","Accessibility","Color systems","Typography","Components"] },
  { id: 6, name: "Frontend Expert", role: "Frontend", icon: "Layout", category: "Engineering",
    summary: "Builds modern web and cross-platform UIs.",
    supports: ["React","Next.js","Vue","Angular","Svelte","Remix","Astro","Nuxt","Flutter","React Native","Ionic"],
    responsibilities: ["Build UI","Optimize rendering","State management","Forms","Authentication","Responsive layouts"] },
  { id: 7, name: "Backend Expert", role: "Backend", icon: "Server", category: "Engineering",
    summary: "Designs APIs, auth, and business logic across major stacks.",
    supports: ["Node","Express","NestJS","FastAPI","Django","Flask","Spring Boot","Laravel","ASP.NET","Go","Rust","Elixir","Phoenix"],
    responsibilities: ["APIs","Authentication","Authorization","Business logic","Caching","Background jobs","Message queues"] },
  { id: 8, name: "Database Engineer", role: "Data", icon: "Database", category: "Engineering",
    summary: "Schemas, migrations, indexes, and query optimization.",
    supports: ["PostgreSQL","MySQL","SQL Server","Oracle","MongoDB","DynamoDB","Cassandra","Redis","Firebase","Supabase","SQLite"],
    responsibilities: ["Database optimization","ER diagrams","Migrations","Indexes","Query optimization","Data integrity"] },
  { id: 9, name: "DevOps Engineer", role: "DevOps", icon: "Cog", category: "Ops",
    summary: "Automates delivery with containers, CI/CD, and IaC.",
    supports: ["Docker","Kubernetes","GitHub Actions","Azure DevOps","Jenkins","CircleCI","GitLab CI","Terraform","Helm","Nginx"],
    responsibilities: ["Deployment","CI/CD","Containers","Infrastructure","Monitoring","Rollbacks"] },
  { id: 10, name: "Cloud Engineer", role: "Cloud", icon: "Cloud", category: "Ops",
    summary: "Provisions scalable, secure cloud infrastructure.",
    supports: ["AWS","Azure","Google Cloud","DigitalOcean","Railway","Render","Fly.io","Vercel","Netlify"],
    responsibilities: ["Infrastructure","Scaling","IAM","Serverless","CDN","Load balancing"] },
  { id: 11, name: "AI/ML Engineer", role: "AI", icon: "BrainCircuit", category: "Engineering",
    summary: "Integrates models, RAG, agents, and vector search.",
    supports: ["TensorFlow","PyTorch","LangChain","LlamaIndex","OpenAI","Anthropic","Gemini","DeepSeek","Ollama","Hugging Face"],
    responsibilities: ["AI integration","Fine tuning","Vector search","RAG","Agents","Prompt engineering"] },
  { id: 12, name: "Security Engineer", role: "Security", icon: "ShieldCheck", category: "Quality",
    summary: "Threat modeling, secrets, encryption, compliance.",
    responsibilities: ["OWASP","Threat modeling","Dependency scanning","Secret detection","Secure authentication","Encryption","Penetration testing","Compliance"] },
  { id: 13, name: "QA Engineer", role: "Testing", icon: "TestTube2", category: "Quality",
    summary: "Automates unit, integration, E2E, and load tests.",
    supports: ["Jest","Vitest","Cypress","Playwright","Selenium","JUnit"],
    responsibilities: ["Unit testing","Integration testing","Regression","Load testing","UI testing","Acceptance testing"] },
  { id: 14, name: "Performance Engineer", role: "Performance", icon: "Gauge", category: "Quality",
    summary: "Profiles hot paths and eliminates bottlenecks.",
    responsibilities: ["Profiling","Optimization","Memory leaks","CPU analysis","Query optimization","Bundle analysis"] },
  { id: 15, name: "Refactoring Agent", role: "Code health", icon: "Wand2", category: "Quality",
    summary: "Applies SOLID, removes duplication, modularizes code.",
    responsibilities: ["Improve readability","Remove duplication","SOLID","Clean Code","Modularization","Dead code removal"] },
  { id: 16, name: "Documentation Agent", role: "Docs", icon: "BookOpen", category: "Support",
    summary: "READMEs, API docs, wikis, and user manuals.",
    responsibilities: ["README","Wiki","Architecture docs","API docs","SDK docs","User manuals","Installation guides"] },
  { id: 17, name: "Debugging Specialist", role: "Debug", icon: "Bug", category: "Quality",
    summary: "Reads traces, forms hypotheses, and won't quit until fixed.",
    responsibilities: ["Read logs","Analyze stack traces","Reproduce bugs","Identify root causes","Recommend fixes","Apply fixes","Verify solutions","Try alternative hypotheses"] },
  { id: 18, name: "Code Reviewer", role: "Review", icon: "GitPullRequest", category: "Quality",
    summary: "Reviews PRs for standards, security, and architecture.",
    responsibilities: ["Review pull requests","Suggest improvements","Detect vulnerabilities","Check standards","Verify architecture"] },
  { id: 19, name: "GitHub Specialist", role: "SCM", icon: "Github", category: "Ops",
    summary: "Repos, PRs, Actions, Projects, Packages, security.",
    knowledge: ["Git","GitHub","GitHub Actions","GitHub Projects","GitHub Packages","GitHub Security","Dependabot","Copilot"],
    responsibilities: ["Create repositories","Branching","Pull Requests","Merge conflicts","Release management","Issue management","Labels","Discussions","Milestones","Actions workflows"] },
  { id: 20, name: "Git Specialist", role: "Git", icon: "GitBranch", category: "Ops",
    summary: "Rebase, cherry-pick, squash, bisect, hooks.",
    knowledge: ["Rebase","Cherry-pick","Squash","Merge","Stash","Hooks","Bisect","Reflog"],
    responsibilities: ["Advanced Git workflows"] },
  { id: 21, name: "Package Manager Expert", role: "Packages", icon: "Package", category: "Ops",
    summary: "Dependency lifecycles across ecosystems.",
    supports: ["npm","pnpm","yarn","bun","pip","poetry","cargo","composer","maven","gradle"],
    responsibilities: ["Install","Upgrade","Lockfiles","Audits","Resolutions"] },
  { id: 22, name: "Legacy Migration Agent", role: "Migration", icon: "ArrowLeftRight", category: "Specialty",
    summary: "Modernizes VB6, Delphi, WinForms, PHP and more.",
    supports: ["VB6","Delphi","WinForms","PHP","ASP.NET","Java Swing","AngularJS"],
    responsibilities: ["Analyze legacy code","Plan migration","Rewrite in modern stacks"] },
  { id: 23, name: "Mobile Specialist", role: "Mobile", icon: "Smartphone", category: "Specialty",
    summary: "Native and cross-platform mobile apps.",
    supports: ["Flutter","React Native","Kotlin","Swift","Xamarin","Ionic"],
    responsibilities: ["Mobile UI","Native integrations","App store delivery"] },
  { id: 24, name: "Desktop Specialist", role: "Desktop", icon: "Monitor", category: "Specialty",
    summary: "Cross-platform desktop apps.",
    supports: ["Electron","Tauri",".NET MAUI","Qt","JavaFX"],
    responsibilities: ["Windowing","Native APIs","Packaging"] },
  { id: 25, name: "Game Development Agent", role: "Games", icon: "Gamepad2", category: "Specialty",
    summary: "Game engines and gameplay systems.",
    supports: ["Unity","Unreal","Godot","Phaser"],
    responsibilities: ["Gameplay","Scenes","Physics","Shaders"] },
  { id: 26, name: "Blockchain Agent", role: "Web3", icon: "Link2", category: "Specialty",
    summary: "Smart contracts and on-chain systems.",
    supports: ["Solidity","Ethereum","Hyperledger","Solana","Rust"],
    responsibilities: ["Smart contracts","Wallets","Audits"] },
  { id: 27, name: "Embedded Systems Agent", role: "Embedded", icon: "Cpu", category: "Specialty",
    summary: "Microcontrollers and RTOS firmware.",
    supports: ["Arduino","ESP32","STM32","Raspberry Pi","RTOS"],
    responsibilities: ["Firmware","Peripherals","Real-time constraints"] },
  { id: 28, name: "Data Engineering Agent", role: "Data eng", icon: "Workflow", category: "Data",
    summary: "Pipelines, warehousing, and orchestration.",
    supports: ["Apache Spark","Kafka","Airflow","dbt","Snowflake","BigQuery"],
    responsibilities: ["ETL","Streaming","Modeling"] },
  { id: 29, name: "Data Science Agent", role: "DS", icon: "LineChart", category: "Data",
    summary: "Analysis, statistics, and ML foundations.",
    supports: ["pandas","NumPy","SciPy","Scikit-learn","R"],
    responsibilities: ["EDA","Modeling","Reporting"] },
  { id: 30, name: "Automation Agent", role: "Automation", icon: "Zap", category: "Specialty",
    summary: "Scripting and workflow automation.",
    supports: ["PowerShell","Bash","Python","AutoHotkey","Robot Framework"],
    responsibilities: ["Scheduled tasks","Scripts","Bots"] },
  { id: 31, name: "Web Scraping Agent", role: "Scraping", icon: "Globe", category: "Specialty",
    summary: "Robust crawlers with rendering support.",
    supports: ["Playwright","Puppeteer","Selenium","BeautifulSoup","Scrapy"],
    responsibilities: ["Selectors","Anti-bot","Pipelines"] },
  { id: 32, name: "API Integration Agent", role: "Integrations", icon: "Plug", category: "Engineering",
    summary: "Any protocol, any provider.",
    supports: ["REST","GraphQL","gRPC","SOAP","WebSockets","MQTT"],
    responsibilities: ["Clients","Auth","Rate limits","Retries"] },
  { id: 33, name: "Dev Environment Agent", role: "IDE", icon: "Terminal", category: "Support",
    summary: "Sets up IDEs, editors, and toolchains.",
    supports: ["VS Code","Visual Studio","Cursor","Windsurf","Zed","JetBrains","Eclipse","Xcode","Android Studio","Vim","Emacs"],
    responsibilities: ["Configs","Extensions","Debuggers"] },
  { id: 34, name: "Prompt Engineering Agent", role: "Prompts", icon: "MessageSquareCode", category: "AI",
    summary: "Designs, evaluates, and tunes prompts.",
    responsibilities: ["Generate prompts","Optimize prompts","Evaluate prompts","Multi-model prompts"] },
  { id: 35, name: "Knowledge Agent", role: "Memory", icon: "Library", category: "Support",
    summary: "Team memory, standards, decisions, lessons.",
    responsibilities: ["Documentation","Design decisions","Coding standards","Team memory","Lessons learned"] },
  { id: 36, name: "Research Agent", role: "Research", icon: "Search", category: "Support",
    summary: "Reads RFCs, specs, and compares libraries.",
    responsibilities: ["Search documentation","Read RFCs","Read standards","Compare libraries","Evaluate frameworks"] },
  { id: 37, name: "Dependency Management Agent", role: "Deps", icon: "PackageCheck", category: "Ops",
    summary: "Safe upgrades with breakage detection.",
    responsibilities: ["Detect outdated packages","Upgrade safely","Verify compatibility","Detect breaking changes"] },
  { id: 38, name: "Release Manager", role: "Releases", icon: "Rocket", category: "Ops",
    summary: "SemVer, changelogs, deployment plans.",
    responsibilities: ["Semantic versioning","Release notes","Changelog","Deployment plans"] },
  { id: 39, name: "Incident Response Agent", role: "SRE", icon: "AlertTriangle", category: "Ops",
    summary: "Triage, rollback, postmortems.",
    responsibilities: ["Production monitoring","Error triage","Rollback","Postmortems"] },
  { id: 40, name: "Polyglot Programming Expert", role: "Languages", icon: "Code2", category: "Engineering",
    summary: "Strong competence across 35+ languages.",
    supports: ["C","C++","C#","Java","Kotlin","Python","JavaScript","TypeScript","Go","Rust","Swift","Dart","PHP","Ruby","Scala","Elixir","Haskell","Julia","R","MATLAB","SQL","Bash","PowerShell","Lua","Perl","Objective-C","COBOL","Fortran","Zig","Assembly","Solidity","F#","OCaml","Erlang","Groovy","Visual Basic"],
    responsibilities: ["Language selection","Idiomatic code","Interop"] },
];

export const CATEGORIES = ["All","Core","Design","Engineering","Data","Ops","Quality","Specialty","AI","Support"] as const;

export const CROSS_CUTTING = [
  { title: "Long-term Memory", desc: "Indexed retrieval across the whole project history." },
  { title: "Structured Planning", desc: "Plan before implementation on any non-trivial task." },
  { title: "Confidence & Assumptions", desc: "Explicit uncertainty and stated assumptions." },
  { title: "Auto Validation", desc: "Lint, typecheck, tests, and static analysis run automatically." },
  { title: "Safe Checkpoints", desc: "Rollback points before every major code change." },
  { title: "Multi-model Orchestration", desc: "Best model per task by capability, cost, latency, context." },
  { title: "Context Management", desc: "Understands large codebases without losing critical info." },
  { title: "Incremental Editing", desc: "Surgical diffs instead of full rewrites." },
  { title: "Observability", desc: "Logs, metrics, traces, and execution history." },
  { title: "Local / Offline", desc: "Runs against local models when appropriate." },
  { title: "Plugin Architecture", desc: "Extend capabilities without touching the core." },
  { title: "Policy-driven Security", desc: "Secrets, permissions, and guardrails." },
  { title: "Human-in-the-loop", desc: "Approval for destructive or high-risk actions." },
  { title: "Auto Docs & Tests", desc: "Docs, diagrams, tests, and migration notes with every change." },
];

export const WORKFLOW = [
  "Analyze project","Build plan","Design architecture","Generate scaffolding","Write code","Create tests","Execute tests","Debug failures","Refactor","Review","Update docs","Commit","Open PR","Address reviews","Prepare release","Deploy","Monitor","Respond to incidents","Learn & memorize",
];

export const INTEGRATIONS = [
  "GitHub","GitLab","Bitbucket","Local Git","VS Code","JetBrains","Visual Studio","Cursor","Windsurf","Zed","CLI","MCP Servers","Docker","Dev Containers","CI/CD","Package Registries","Issue Trackers","Docs","Cloud Platforms","Observability",
];
