import { createFileRoute, Link } from "@tanstack/react-router";
import * as Icons from "lucide-react";
import { useMemo, useState } from "react";

export const Route = createFileRoute("/agent-run")({
  head: () => ({ meta: [{ title: "Agent Run Center — Work" }, { name: "description", content: "Observe governed AI engineering runs, context, agents, models and verification." }] }),
  component: AgentRunCenter,
});

const stages = [
  ["Context Broker", "Complete", "Repository indexed and task context assembled.", Icons.BrainCircuit],
  ["Architect", "Complete", "Execution approach and affected modules identified.", Icons.Landmark],
  ["Backend Engineer", "Working", "Inspecting authentication services and session handling.", Icons.ServerCog],
  ["Database Engineer", "Working", "Checking user, session and recovery data paths.", Icons.Database],
  ["Security Engineer", "Waiting", "Queued after implementation proposal.", Icons.ShieldCheck],
  ["QA Engineer", "Waiting", "Verification begins after changes are approved.", Icons.TestTube2],
] as const;

function AgentRunCenter() {
  const [paused, setPaused] = useState(false);
  const [showContext, setShowContext] = useState(true);
  const progress = useMemo(() => paused ? 62 : 78, [paused]);
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/85 backdrop-blur-xl"><div className="max-w-[1600px] mx-auto h-16 px-4 lg:px-6 flex items-center justify-between gap-4"><div className="flex items-center gap-3 min-w-0"><Link to="/project-workspace" className="size-8 rounded-lg bg-secondary grid place-items-center"><Icons.ArrowLeft className="size-4"/></Link><div><div className="font-semibold">Agent Run Center</div><div className="text-[10px] font-mono text-muted-foreground">run_8F2A · seller-auth-hardening</div></div></div><div className="flex items-center gap-2"><span className="hidden sm:flex items-center gap-1.5 px-2.5 py-1.5 rounded-full bg-emerald-400/10 text-emerald-400 text-[10px] font-mono"><span className="size-1.5 rounded-full bg-emerald-400 animate-pulse"/> RUNNING</span><button onClick={()=>setPaused(!paused)} className="px-3 py-2 rounded-lg border border-border text-xs hover:bg-secondary">{paused?"Resume":"Pause"}</button><button className="px-3 py-2 rounded-lg border border-destructive/30 text-destructive text-xs hover:bg-destructive/10">Stop run</button></div></div></header>
    <main className="max-w-[1600px] mx-auto p-4 sm:p-6 lg:p-8"><div className="mb-6"><div className="text-[10px] font-mono uppercase tracking-[.2em] text-primary mb-2">Live engineering execution</div><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><h1 className="text-3xl sm:text-4xl font-bold tracking-tight">Seller authentication hardening</h1><p className="mt-2 text-sm text-muted-foreground">BredaBuy Ghana · supervisor workflow · human approval required before writes</p></div><div className="w-full lg:w-80"><div className="flex justify-between text-[10px] text-muted-foreground mb-2"><span>Overall progress</span><span>{progress}%</span></div><div className="h-2 rounded-full bg-secondary overflow-hidden"><div className="h-full bg-gradient-to-r from-primary to-accent transition-all" style={{width:`${progress}%`}}/></div></div></div></div>
      <div className="grid xl:grid-cols-[1.2fr_.8fr] gap-5"><section className="space-y-5"><div className="rounded-2xl border border-border bg-card/70 overflow-hidden"><div className="px-5 py-4 border-b border-border/70 flex justify-between"><div><h2 className="font-semibold">Agent pipeline</h2><p className="text-xs text-muted-foreground mt-1">Supervisor-managed specialist execution</p></div><span className="text-[10px] font-mono text-muted-foreground">6 agents</span></div><div className="p-4 space-y-2">{stages.map(([name,status,detail,Icon])=><div key={name} className="p-3.5 rounded-xl border border-border/70"><div className="flex gap-3"><span className={`size-8 shrink-0 rounded-lg grid place-items-center ${status==="Complete"?"bg-emerald-400/10 text-emerald-400":status==="Working"?"bg-primary/10 text-primary":"bg-secondary text-muted-foreground"}`}><Icon className="size-4"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><div className="text-sm font-medium">{name}</div><span className={`text-[10px] font-mono ${status==="Working"?"text-primary":status==="Complete"?"text-emerald-400":"text-muted-foreground"}`}>{status.toUpperCase()}</span></div><p className="text-xs text-muted-foreground mt-1">{detail}</p>{status==="Working"&&<div className="mt-3 h-1 rounded-full bg-secondary overflow-hidden"><div className="h-full w-[68%] bg-primary animate-pulse"/></div>}</div></div></div>)}</div></div>
      <div className="rounded-2xl border border-border bg-card/70"><div className="px-5 py-4 border-b border-border/70 flex justify-between"><div><h2 className="font-semibold">Live agent activity</h2><p className="text-xs text-muted-foreground mt-1">Recent reasoning events</p></div><span className="size-2 rounded-full bg-primary animate-pulse"/></div><div className="p-5 space-y-4 font-mono text-xs"><Event time="14:22:08" agent="backend" text="Inspecting authentication service..."/><Event time="14:22:14" agent="backend" text="Found 3 related modules."/><Event time="14:22:21" agent="database" text="Checking session and recovery data paths..."/><Event time="14:22:29" agent="backend" text="Preparing implementation proposal." active/></div></div></section>
      <aside className="space-y-5"><section className="rounded-2xl border border-border bg-card/70 p-5"><div className="flex justify-between items-center mb-4"><div><h2 className="font-semibold">Execution context</h2><p className="text-xs text-muted-foreground mt-1">What the model can see</p></div><button onClick={()=>setShowContext(!showContext)} className="text-xs text-primary">{showContext?"Hide":"Show"}</button></div>{showContext&&<><div className="grid grid-cols-3 gap-2 mb-4"><Mini label="Files scanned" value="42"/><Mini label="Relevant" value="11"/><Mini label="Supplied" value="6"/></div><div className="space-y-2 text-xs">{["src/features/auth/AuthService.ts","src/features/sellers/SellerRoutes.tsx","src/lib/session.ts","supabase/migrations/auth.sql","tests/auth/recovery.test.ts"].map(f=><div key={f} className="flex gap-2 items-center px-2.5 py-2 rounded-lg bg-secondary/60 font-mono"><Icons.FileCode2 className="size-3 text-primary shrink-0"/><span className="truncate">{f}</span></div>)}</div></>}</section>
      <section className="rounded-2xl border border-border bg-card/70 p-5"><h2 className="font-semibold">Model</h2><div className="mt-4 p-3 rounded-xl border border-border bg-background/50"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-emerald-400"/><span className="text-sm font-medium">Ollama</span></div><div className="mt-2 text-[11px] font-mono text-muted-foreground">deepseek-coder:6.7b</div><div className="mt-3 flex justify-between text-[10px] text-muted-foreground"><span>Local inference</span><span>Connected</span></div></div></section>
      <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5"><div className="flex items-center gap-2 mb-3"><Icons.ShieldCheck className="size-4 text-primary"/><h2 className="font-semibold">Governance gate</h2></div><div className="space-y-2 text-xs text-muted-foreground"><p>✓ No repository writes performed</p><p>✓ Sandbox execution protected</p><p>✓ Agent outputs are being persisted</p><p className="text-primary">○ Implementation requires approval</p></div><button className="mt-4 w-full py-2.5 rounded-lg border border-primary/30 text-primary text-xs font-medium hover:bg-primary/10">Review proposed changes</button></section></aside></div>
    </main>
  </div>;
}
function Event({time,agent,text,active=false}:{time:string;agent:string;text:string;active?:boolean}){return <div className="flex gap-3"><span className="text-muted-foreground shrink-0">{time}</span><span className="text-primary shrink-0">{agent}</span><span className={active?"text-foreground":"text-muted-foreground"}>{text}{active&&<span className="inline-block w-1.5 h-3 ml-1 align-middle bg-primary animate-pulse"/>}</span></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-border p-2.5 text-center"><div className="text-lg font-semibold">{value}</div><div className="text-[9px] text-muted-foreground">{label}</div></div>}
