import { createFileRoute, Link } from "@tanstack/react-router";
import * as Icons from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/change-review")({
  head: () => ({ meta: [{ title: "Change Review — Work" }, { name: "description", content: "Review AI-proposed engineering changes before execution." }] }),
  component: ChangeReview,
});

const files = [
  { path: "src/features/auth/AuthService.ts", kind: "M", risk: "Medium", summary: "Harden session validation and recovery flow" },
  { path: "src/features/sellers/SellerRoutes.tsx", kind: "M", risk: "Low", summary: "Route unauthenticated users through recovery-safe guards" },
  { path: "tests/auth/recovery.test.ts", kind: "+", risk: "Low", summary: "Add coverage for expired and replayed recovery tokens" },
];

function ChangeReview() {
  const [selected, setSelected] = useState(files[0]);
  const [approved, setApproved] = useState(false);
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/85 backdrop-blur-xl"><div className="max-w-[1600px] mx-auto h-16 px-4 lg:px-6 flex items-center justify-between"><div className="flex items-center gap-3"><Link to="/agent-run" className="size-8 rounded-lg bg-secondary grid place-items-center"><Icons.ArrowLeft className="size-4"/></Link><div><div className="font-semibold">Change Review</div><div className="text-[10px] font-mono text-muted-foreground">run_8F2A · proposed patch</div></div></div><div className="flex items-center gap-2"><span className="px-2.5 py-1.5 rounded-full bg-amber-400/10 text-amber-400 text-[10px] font-mono">AWAITING APPROVAL</span></div></div></header>
    <main className="max-w-[1600px] mx-auto p-4 sm:p-6 lg:p-8"><div className="mb-6"><div className="text-[10px] font-mono uppercase tracking-[.2em] text-primary mb-2">Governed delivery</div><h1 className="text-3xl sm:text-4xl font-bold tracking-tight">Review proposed changes before they ship.</h1><p className="mt-2 text-sm text-muted-foreground max-w-3xl">The agent team has completed analysis and prepared a sandbox-safe patch. Nothing will be written to the repository until you approve it.</p></div>
      <div className="grid xl:grid-cols-[280px_1fr_310px] gap-4"><aside className="rounded-2xl border border-border bg-card/70 p-3 h-fit"><div className="px-2 py-2 mb-1 text-[10px] uppercase tracking-[.18em] text-muted-foreground">Changed files · 3</div>{files.map(f=><button key={f.path} onClick={()=>setSelected(f)} className={`w-full text-left p-3 rounded-xl mb-1 transition ${selected.path===f.path?"bg-primary/10":"hover:bg-secondary"}`}><div className="flex items-center gap-2"><span className={`font-mono text-xs ${f.kind==="+"?"text-emerald-400":"text-amber-400"}`}>{f.kind}</span><span className="text-xs font-medium truncate">{f.path.split("/").pop()}</span></div><div className="text-[10px] text-muted-foreground mt-1 truncate">{f.path}</div><div className="mt-2 flex justify-between"><span className="text-[9px] text-muted-foreground">Risk: {f.risk}</span><Icons.ChevronRight className="size-3 text-muted-foreground"/></div></button>)}</aside>
      <section className="rounded-2xl border border-border bg-card/70 overflow-hidden"><div className="px-5 py-4 border-b border-border/70 flex justify-between gap-3"><div><h2 className="font-semibold">{selected.path}</h2><p className="text-xs text-muted-foreground mt-1">{selected.summary}</p></div><span className="px-2 py-1 rounded-lg bg-amber-400/10 text-amber-400 text-[10px]">{selected.risk} risk</span></div><div className="p-4 space-y-2 font-mono text-xs leading-6 overflow-auto"><CodeLine n="41" old="if (!session) return null;" next="if (!session || session.expiresAt < Date.now()) return null;"/><CodeLine n="42" old="return getSeller(session.userId);" next="return getSeller(session.userId);"/><CodeLine n="43" old="" next=""/><CodeLine n="44" old="" next="return validateRecoveryContext(session);"/><CodeLine n="45" old="" next=""/><CodeLine n="46" old="" next="// Reject replayed recovery sessions before mutation."/></div><div className="px-5 py-4 border-t border-border/70 flex flex-wrap gap-2"><span className="inline-flex items-center gap-1.5 text-[10px] text-emerald-400"><Icons.CheckCircle2 className="size-3"/> Type-safe proposal</span><span className="inline-flex items-center gap-1.5 text-[10px] text-emerald-400"><Icons.CheckCircle2 className="size-3"/> Tests planned</span><span className="inline-flex items-center gap-1.5 text-[10px] text-amber-400"><Icons.AlertTriangle className="size-3"/> Auth behavior changed</span></div></section>
      <aside className="space-y-4"><section className="rounded-2xl border border-border bg-card/70 p-5"><h2 className="font-semibold">AI assessment</h2><div className="mt-4 space-y-3"><Assessment label="Overall risk" value="Medium"/><Assessment label="Files changed" value="3"/><Assessment label="Tests affected" value="4"/><Assessment label="Security impact" value="Reviewed"/></div></section><section className="rounded-2xl border border-border bg-card/70 p-5"><h2 className="font-semibold">Verification plan</h2><ul className="mt-3 space-y-2 text-xs text-muted-foreground"><li>• Run typecheck</li><li>• Run authentication tests</li><li>• Run lint and build</li><li>• Inspect generated diff</li><li>• Create draft PR only if all pass</li></ul></section><section className="rounded-2xl border border-primary/20 bg-primary/5 p-5"><div className="flex items-center gap-2 mb-2"><Icons.ShieldCheck className="size-4 text-primary"/><h2 className="font-semibold text-sm">Human approval</h2></div><p className="text-xs text-muted-foreground leading-5">Approval authorizes sandbox execution of this proposed patch. Repository writes remain gated until verification succeeds.</p><button onClick={()=>setApproved(true)} className="mt-4 w-full py-2.5 rounded-lg bg-primary text-primary-foreground text-xs font-semibold">{approved?"Approved — execution queued":"Approve & execute in sandbox"}</button></section></aside></div></main></div>;
}
function CodeLine({n,old,next}:{n:string;old:string;next:string}){return <div className="grid grid-cols-[38px_1fr] gap-3"><span className="text-muted-foreground/50 text-right">{n}</span><div>{old&&<div className="px-2 rounded bg-destructive/10 text-destructive">- {old}</div>}{next&&<div className="px-2 rounded bg-emerald-400/10 text-emerald-400">+ {next}</div>}</div></div>}
function Assessment({label,value}:{label:string;value:string}){return <div className="flex justify-between text-xs"><span className="text-muted-foreground">{label}</span><span>{value}</span></div>}
