#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
const runtimeRoot=path.dirname(new URL(import.meta.url).pathname);const modelConfig=JSON.parse(fs.readFileSync(path.join(runtimeRoot,'config/models.json'),'utf8'));const agentConfig=JSON.parse(fs.readFileSync(path.join(runtimeRoot,'config/agents.json'),'utf8'));const args=process.argv.slice(2);const command=args[0]||'status';const input=args.slice(1).join(' ').trim();const env=(n,f)=>process.env[n]||f;const ollamaUrl=()=>env('OLLAMA_BASE_URL',modelConfig.providers.ollama.baseUrl);const fail=m=>{console.error(`work: ${m}`);process.exit(1)};const run=(name,a,cwd=process.cwd())=>execFileSync(name,a,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']});
function findProjectRoot(start=process.cwd()){let c=path.resolve(start);while(c!==path.dirname(c)){if(fs.existsSync(path.join(c,'.git'))||fs.existsSync(path.join(c,'package.json'))||fs.existsSync(path.join(c,'pyproject.toml')))return c;c=path.dirname(c)}return path.resolve(start)}
function readJson(f){try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return null}}
function detectProject(root){const pkg=readJson(path.join(root,'package.json'));const files=new Set(fs.readdirSync(root,{withFileTypes:true}).map(e=>e.name));const deps={...(pkg?.dependencies||{}),...(pkg?.devDependencies||{})};const tech=[];for(const [k,l] of [['react','React'],['next','Next.js'],['vite','Vite'],['typescript','TypeScript'],['tailwindcss','Tailwind CSS'],['@tanstack/react-router','TanStack Router'],['@supabase/supabase-js','Supabase'],['@nestjs/core','NestJS'],['express','Express'],['prisma','Prisma'],['@prisma/client','Prisma'],['playwright','Playwright'],['@playwright/test','Playwright'],['vitest','Vitest']])if(deps[k])tech.push(l);if(files.has('pyproject.toml')||files.has('requirements.txt'))tech.push('Python');if(files.has('Dockerfile')||files.has('docker-compose.yml')||files.has('compose.yml'))tech.push('Docker');if(files.has('.github'))tech.push('GitHub Actions');if(files.has('.devcontainer'))tech.push('Dev Container');return{root,name:pkg?.name||path.basename(root),packageManager:pkg?(files.has('pnpm-lock.yaml')?'pnpm':files.has('yarn.lock')?'yarn':files.has('bun.lock')||files.has('bun.lockb')?'bun':'npm'):null,technologies:[...new Set(tech)]}}
function collectContext(){const root=findProjectRoot(),project=detectProject(root);let branch='(unknown)',status='(not a git repository)';try{branch=run('git',['branch','--show-current'],root).trim()||'(detached)';status=run('git',['status','--short'],root)||'(clean)'}catch{}let instructions='';for(const n of ['AGENTS.md','WORK.md','CLAUDE.md','.github/copilot-instructions.md']){const f=path.join(root,n);if(fs.existsSync(f))instructions+=`\n--- ${n} ---\n${fs.readFileSync(f,'utf8').slice(0,12000)}`}const workDir=path.join(root,'.work');return{...project,branch,gitStatus:status,instructions,workDir,manifest:readJson(path.join(workDir,'project.json'))}}
function help(){console.log(`\nwork — cross-project AI engineering control plane\n\n work init\n work status | doctor | context | audit\n work memory add "note" | work memory list\n work agents | models\n work plan "task"\n work route "task"\n work sandbox create|remove|status <task-id>\n work patch <task-id> propose|validate|apply\n work exec <task-id>\n work task create|list|show|approve|cancel|run ...\n work "task" | work debug "task" | work review [path]\n work mcp\n`) }
function modelFor(role='coding'){const item=modelConfig.providers.ollama.models[role]||modelConfig.providers.ollama.models.coding;return env(item.env,item.default)}
function initProject(){const c=collectContext(),d=c.workDir;for(const x of ['memory','tasks','decisions','sessions','sandboxes'])fs.mkdirSync(path.join(d,x),{recursive:true});const m=c.manifest||{schemaVersion:'1.0',project:{name:c.name,stack:c.technologies,packageManager:c.packageManager},defaults:{workflow:'build',modelRole:'coding'},permissions:{read:'allow',search:'allow',write:'ask',shell:'ask',gitCommit:'ask',gitPush:'ask',deploy:'deny'}};fs.writeFileSync(path.join(d,'project.json'),JSON.stringify(m,null,2)+'\n');if(!fs.existsSync(path.join(d,'.gitignore')))fs.writeFileSync(path.join(d,'.gitignore'),'sessions/\nsandboxes/\n*.log\n');if(!fs.existsSync(path.join(d,'README.md')))fs.writeFileSync(path.join(d,'README.md'),`# Work project state\n\nManaged by AI Engineering Studio. Project: ${c.name}.\n`);console.log(`Initialized Work project state in ${d}`)}
function memory(action,note){const c=collectContext(),f=path.join(c.workDir,'memory','notes.md');fs.mkdirSync(path.dirname(f),{recursive:true});if(action==='add'){if(!note)fail('memory add requires text');fs.appendFileSync(f,`- ${new Date().toISOString()} — ${note}\n`);console.log('Memory recorded.')}else if(action==='list')console.log(fs.existsSync(f)?fs.readFileSync(f,'utf8'):'(no project memory yet)');else fail('Usage: work memory add "note" | work memory list')}
function audit(){const c=collectContext();console.log(JSON.stringify({project:c.name,root:c.root,stack:c.technologies,checks:{projectInitialized:Boolean(c.manifest),gitRepository:fs.existsSync(path.join(c.root,'.git')),instructions:Boolean(c.instructions),envExample:fs.existsSync(path.join(c.root,'.env.example')),tests:['vitest.config.ts','playwright.config.ts','jest.config.js'].some(f=>fs.existsSync(path.join(c.root,f))),ci:fs.existsSync(path.join(c.root,'.github','workflows')),devcontainer:fs.existsSync(path.join(c.root,'.devcontainer'))}},null,2))}
function classify(text){const t=text.toLowerCase();if(/security|vulnerab|permission|auth/.test(t))return'reasoning';if(/debug|error|fail|broken|architecture|design|deploy|release/.test(t))return'reasoning';if(/code|implement|refactor|typescript|react|python|sql|test|feature|build/.test(t))return'coding';return'fast'}
function generate(prompt,model){try{const o=run('curl',['-fsS',`${ollamaUrl()}/api/generate`,'-H','Content-Type: application/json','-d',JSON.stringify({model,prompt,stream:false,options:{temperature:0.2}})]);console.log(JSON.parse(o).response||o)}catch{fail(`Ollama is unavailable at ${ollamaUrl()}. Run 'work doctor'.`)}}
if(['help','--help','-h'].includes(command)){help();process.exit(0)}if(command==='init'){initProject();process.exit(0)}if(command==='memory'){memory(args[1],args.slice(2).join(' '));process.exit(0)}if(command==='audit'){audit();process.exit(0)}if(command==='agents'){for(const a of agentConfig.agents)console.log(`${a.id.padEnd(14)} ${a.role.padEnd(30)} ${a.modelRole}`);process.exit(0)}if(command==='models'){console.log(`Ollama URL: ${ollamaUrl()}`);for(const r of ['coding','reasoning','fast','general'])console.log(`${r.padEnd(10)} ${modelFor(r)}`);process.exit(0)}if(command==='context'){console.log(JSON.stringify(collectContext(),null,2));process.exit(0)}if(command==='mcp'){execFileSync(process.execPath,[path.join(runtimeRoot,'work-mcp.mjs')],{stdio:'inherit'});process.exit(0)}if(command==='status'||command==='doctor'){const c=collectContext();console.log(`Project: ${c.name}\nRoot:    ${c.root}\nBranch:  ${c.branch}\nStack:   ${c.technologies.join(', ')||'undetected'}\nWork:    ${c.manifest?'initialized':'not initialized'}`);try{const d=JSON.parse(run('curl',['-fsS',`${ollamaUrl()}/api/tags`]));console.log(`Ollama:  ONLINE (${ollamaUrl()})\nModels:  ${(d.models||[]).map(m=>m.name).join(', ')||'(none)'}`)}catch{console.log(`Ollama:  OFFLINE (${ollamaUrl()})`);if(command==='doctor')process.exitCode=1}process.exit()}if(command==='plan'){const task=args.slice(1).join(' ');if(!task)fail('usage: work plan "task"');execFileSync(process.execPath,[path.join(runtimeRoot,'work-plan.mjs'),task],{stdio:'inherit'});process.exit(0)}if(command==='route'){const task=args.slice(1).join(' ');if(!task)fail('usage: work route "task"');execFileSync(process.execPath,[path.join(runtimeRoot,'work-route.mjs'),task],{stdio:'inherit'});process.exit(0)}if(command==='sandbox'){execFileSync(process.execPath,[path.join(runtimeRoot,'work-sandbox.mjs'),...args.slice(1)],{stdio:'inherit'});process.exit(0)}if(command==='patch'){const task=args[1],action=args[2]||'propose';if(!task)fail('usage: work patch <task-id> propose|validate|apply');execFileSync(process.execPath,[path.join(runtimeRoot,'work-patch.mjs'),task,action],{stdio:'inherit'});process.exit(0)}if(command==='exec'){const task=args[1];if(!task)fail('usage: work exec <task-id>');execFileSync(process.execPath,[path.join(runtimeRoot,'work-exec.mjs'),task],{stdio:'inherit'});process.exit(0)}
const mode=['debug','review'].includes(command)?command:'ask';const task=input||(mode==='review'&&args[0]?`Review ${args[0]}`:args.join(' '));if(!task){help();process.exit(0)}const role=classify(task);const c=collectContext();const prompt=`You are the Work Orchestrator in a multi-agent software engineering team.\nProject: ${c.name}\nRepository: ${c.root}\nTechnology: ${c.technologies.join(', ')||'unknown'}\nBranch: ${c.branch}\nGit status:\n${c.gitStatus}\nProject manifest: ${JSON.stringify(c.manifest||{})}\n${c.instructions}\n\nTask:\n${task}\n\nRules: Do not invent APIs or files. State assumptions. Prefer small, verifiable changes. Never claim a change was made unless a tool actually made it. Recommend the appropriate specialist agent and concrete next steps.`;generate(prompt,modelFor(role));
